# Generated by Django 4.2.25 on 2025-10-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('disputed', 'Disputed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('misleading', 'Misleading'), ('unsupported', 'Unsupported'), ('inconclusive', 'Inconclusive')], default='inconclusive', max_length=32)),
                ('summary', models.TextField(blank=True, null=True)),
                ('confidance', models.FloatField(default=0.0)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='api.claim')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField(blank=True, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField()),
                ('supporting_doi', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.claim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source')),
            ],
            options={
                'unique_together': {('claim', 'source')},
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='sources',
            field=models.ManyToManyField(blank=True, through='api.ClaimSource', to='api.source'),
        ),
    ]
