# Generated by Django 4.2.25 on 2025-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
