# Generated by Django 4.2.25 on 2025-11-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_claim_text_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationresult',
            old_name='confidance',
            new_name='confidence',
        ),
    ]
