# Generated by Django 4.2.25 on 2025-11-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_confidance_verificationresult_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dispute', 'verbose_name_plural': 'Disputes'},
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='reporter_contact',
        ),
        migrations.AddField(
            model_name='dispute',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='supporting_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='api.claim'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='supporting_file',
            field=models.FileField(blank=True, null=True, upload_to='disputes/'),
        ),
    ]
