# Generated by Django 4.2.25 on 2025-11-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_dispute_original_confidence_dispute_original_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.claim'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='claim_text',
            field=models.TextField(help_text='Teks klaim yang dilaporkan'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='original_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.TextField(help_text='Alasan pelaporan'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reporter_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reporter_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='supporting_doi',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='supporting_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
