# Generated by Django 4.2.25 on 2025-11-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dispute_claim_alter_dispute_claim_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='credibility_score',
            field=models.FloatField(default=0.5, help_text='Skor kredibilitas 0.0 - 1.0'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('website', 'Website'), ('journal', 'Journal'), ('news', 'News'), ('government', 'Government'), ('organization', 'Organization'), ('other', 'Other')], default='website', help_text='Tipe sumber', max_length=50),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
