# Generated by Django 4.2.25 on 2025-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_source_credibility_score_source_source_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimsource',
            options={'ordering': ['rank']},
        ),
        migrations.AddIndex(
            model_name='claimsource',
            index=models.Index(fields=['claim', 'source'], name='api_claimso_claim_i_5b7748_idx'),
        ),
        migrations.AddIndex(
            model_name='claimsource',
            index=models.Index(fields=['rank'], name='api_claimso_rank_e4da79_idx'),
        ),
    ]
