# Generated by Django 4.2.25 on 2025-11-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_claimsource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationresult',
            name='label',
            field=models.CharField(choices=[('valid', 'Valid'), ('hoax', 'Hoax'), ('uncertain', 'Tidak Tentu'), ('unverified', 'Tidak Terverifikasi')], default='unverified', max_length=32),
        ),
    ]
