# Generated by Django 4.2.25 on 2025-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_verificationresult_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationresult',
            name='logic_version',
            field=models.CharField(default='v1.0', help_text='Version of verification logic used', max_length=10),
        ),
        migrations.AddIndex(
            model_name='verificationresult',
            index=models.Index(fields=['claim', 'logic_version'], name='api_verific_claim_i_9d82e2_idx'),
        ),
    ]
