# Generated by Django 4.2.25 on 2025-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_verificationresult_logic_version_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationresult',
            name='api_verific_claim_i_9d82e2_idx',
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='logic_version',
            field=models.CharField(default='v1.0', max_length=32, null=True),
        ),
    ]
