# Generated by Django 4.2.25 on 2025-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_verificationresult_api_verific_claim_i_9d82e2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationresult',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='label',
            field=models.CharField(choices=[('valid', 'FAKTA'), ('hoax', 'HOAX'), ('uncertain', 'TIDAK PASTI'), ('unverified', 'TIDAK TERVERIFIKASI')], default='unverified', max_length=32),
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='logic_version',
            field=models.CharField(default='v2.0', max_length=32, null=True),
        ),
    ]
