# Generated by Django 4.2.25 on 2025-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_verificationresult_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='normalized_text',
            new_name='text_normalized',
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['text_hash'], name='api_claim_text_ha_1e98c8_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['text_normalized'], name='api_claim_text_no_e5ea96_idx'),
        ),
    ]
