# Generated by Django 4.2.25 on 2025-12-02 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_rename_normalized_text_claim_text_normalized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField()),
                ('authors', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=500, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source_portal', models.CharField(choices=[('sinta', 'SINTA'), ('garuda', 'Garuda'), ('doaj', 'DOAJ'), ('google_scholar', 'Google Scholar'), ('other', 'Other')], default='other', max_length=50)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('is_embedded', models.BooleanField(default=False)),
                ('credibility_score', models.FloatField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doi'], name='api_journal_doi_c0cc06_idx'), models.Index(fields=['title'], name='api_journal_title_8a6167_idx'), models.Index(fields=['is_embedded'], name='api_journal_is_embe_541ee6_idx')],
            },
        ),
    ]
